services:
  - type: web
    name: psystudio-license-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: license-data
      mountPath: /app/data
      sizeGB: 1
